POST http://localhost:5678/api/groups
Content-Type: application/json

{
  "name": "jp[1",
  "isPrivate": false,
  "nextRoundDate": "2022-10-11",
  "intervalDays": 10
}

###

GET http://localhost:5678/api/Groups?userId=43ef1000-0000-0000-0000-000000000000
Content-Type: application/json

###

GET http://localhost:5678/api/Groups/9f048110-0000-0000-0000-000000000000
Content-Type: application/json

###

POST http://localhost:5678/api/Groups/9f048110-0000-0000-0000-000000000000/join
Content-Type: application/json

###

POST http://localhost:5678/api/Groups/9f048110-0000-0000-0000-000000000000/make-round
Content-Type: application/json

###

POST http://localhost:5678/api/Users
Content-Type: application/json

{
  "firstName": "FirstName",
  "lastName": "LastNameovich",
  "email": "test@mail.ru"
}

###

GET http://localhost:5678/api/Users?groupId=9f048110-0000-0000-0000-000000000000
Content-Type: application/json

###

GET http://localhost:5678/api/Users/43ef1000-0000-0000-0000-000000000000
Content-Type: application/json